### ISSUE TITLE
This and other wet-boew repositories lack a license

### ISSUE THREAD

**Issue by jpmckinney** [wet-boew/wet-boew-wordpress#39]
I can't determine the license of the following repositories (which includes this one). Can a `Licence-fr.txt` and `Licence-en.txt` be added to these, like with https://github.com/wet-boew/wet-boew ?

* https://github.com/wet-boew/codefest
* https://github.com/wet-boew/codefest-transcripts
* https://github.com/wet-boew/gcweb-experimental
* https://github.com/wet-boew/techspecs
* https://github.com/wet-boew/theme-gcweb
* https://github.com/wet-boew/themes-cdn
* https://github.com/wet-boew/themes-dist
* https://github.com/wet-boew/web-reporting
* https://github.com/wet-boew/wet-boew-aem
* https://github.com/wet-boew/wet-boew-api
* https://github.com/wet-boew/wet-boew-api-standards
* https://github.com/wet-boew/wet-boew-attachments
* https://github.com/wet-boew/wet-boew-cdn
* https://github.com/wet-boew/wet-boew-ckeditor
* https://github.com/wet-boew/wet-boew-codecharge
* https://github.com/wet-boew/wet-boew-dist-legacy
* https://github.com/wet-boew/wet-boew-docpad
* https://github.com/wet-boew/wet-boew-documentation
* https://github.com/wet-boew/wet-boew-dotnet
* https://github.com/wet-boew/wet-boew-dotnetnuke
* https://github.com/wet-boew/wet-boew-drupal
* https://github.com/wet-boew/wet-boew-drupal8
* https://github.com/wet-boew/wet-boew-elgg
* https://github.com/wet-boew/wet-boew-experimental
* https://github.com/wet-boew/wet-boew-java-maven
* https://github.com/wet-boew/wet-boew-joomla
* https://github.com/wet-boew/wet-boew-legacy
* https://github.com/wet-boew/wet-boew-mobiledevicebasedapps
* https://github.com/wet-boew/wet-boew-multimedia-fallback
* https://github.com/wet-boew/wet-boew-php
* https://github.com/wet-boew/wet-boew-sharepoint
* https://github.com/wet-boew/wet-boew-ssi
* https://github.com/wet-boew/wet-boew-student-project
* https://github.com/wet-boew/wet-boew-styleguide
* https://github.com/wet-boew/wet-boew-wordpress
* https://github.com/wet-boew/wet-boew-wpss
* https://github.com/wet-boew/wet-boew.github.io
* https://github.com/wet-boew/wiwg_api_current-infrastructure
* https://github.com/wet-boew/wiwg_api_use-cases
* https://github.com/wet-boew/wiwg_html-data_core-types
* https://github.com/wet-boew/wiwg_html-data_use-cases

**Comment by nschonni** [comment]
This is probably better to open on the main repo since there aren't many people watching this
> https://github.com/wet-boew/themes-cdn

Has license on the actual content/branches, but this is just a fake CDN

> https://github.com/wet-boew/themes-dist

Same as the themes-cdn for gh-pages reading a-la-rawgithub

A bunch of other should probably just be deleted since they have no code or issues in them. Not sure who has the org-admin permissions to do that now.

**Comment by jpmckinney** [comment]
Opened https://github.com/wet-boew/wet-boew/issues/7849 instead.
